DROP TABLE IF EXISTS `ai_playerbot_arena_team_names`;
CREATE TABLE `ai_playerbot_arena_team_names` (
  `name_id` mediumint(8) NOT NULL AUTO_INCREMENT UNIQUE,
  `name` varchar(24) NOT NULL UNIQUE,
  `type` TINYINT(3) NOT NULL,
  PRIMARY KEY (`name_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED COMMENT='PlayerbotAI arena team names';



LOCK TABLES `ai_playerbot_arena_team_names` WRITE;
INSERT INTO `ai_playerbot_arena_team_names` (`name_id`,`name`, `type`) VALUES

(NULL, 'out of coverage',2),
(NULL, 'Dead or Alive',2),
(NULL, 'Noßrain',2),
(NULL, 'Истребление',2),
(NULL, 'Pieces',2),
(NULL, 'ßurst',2),
(NULL, 'hey im actually not mvp',2),
(NULL, 'Group Therapy',2),
(NULL, 'Outland Elite',2),
(NULL, 'Исчадье Тьмы',2),
(NULL, 'Dun Spetsnaz',2),
(NULL, 'ЧСВ РБГ',2),
(NULL, 'ShameReborn',2),
(NULL, 'TEAM VÉSUVE',2),
(NULL, 'Battle for Apes',2),
(NULL, 'Can You Feel It',2),
(NULL, 'Zero to Hero',2),
(NULL, 'Link Curve',2),
(NULL, 'Project',2),
(NULL, 'Security',2),
(NULL, 'Skill Loading',2),
(NULL, 'Cya Bro',2),
(NULL, 'out of rage',2),
(NULL, 'Improve',2),
(NULL, 'WORST GENERATION',2),
(NULL, 'KFC Fitness Club',2),
(NULL, 'unlucky',2),
(NULL, 'OldStyle',2),
(NULL, 'Walkthrough',2),
(NULL, 'Лё Резистанс',2),
(NULL, 'League of Gladiators',2),
(NULL, 'Practice',2),
(NULL, 'Rofl So Bad',2),
(NULL, 'Synergy',2),
(NULL, 'Que la famille',2),
(NULL, 'Древние баги',2),
(NULL, 'Echo',2),
(NULL, 'KARMA',2),
(NULL, 'Exodus',2),
(NULL, 'Felsenfest',2),
(NULL, 'LifeIsPain',2),
(NULL, 'The Eternal',2),
(NULL, 'Raid Trap',2),
(NULL, 'The Dambusters',2),
(NULL, 'Станция Токсичных',2),
(NULL, 'Cykla Blöt',2),
(NULL, 'Ethics',2),
(NULL, 'Human ZOO',2),
(NULL, 'Mausoleum',2),
(NULL, 'Nashwan GoDs',2),
(NULL, 'PASTIS PETANQUE ARENE',2),
(NULL, 'tweet holinka',2),
(NULL, 'Пять Бутылок Водки',2),
(NULL, 'РЕТРИК РУКИ ПОЛТОРАШКИ',2),
(NULL, 'У беляша',2),
(NULL, 'A M K',2),
(NULL, 'Against The WorId',2),
(NULL, 'Dilemma',2),
(NULL, 'Efficiency',2),
(NULL, 'Halcyon',2),
(NULL, 'I SoliD I',2),
(NULL, 'Impact',2),
(NULL, 'Melk Trupp',2),
(NULL, 'Tatortreiniger',2),
(NULL, 'TG Gaming',2),
(NULL, 'Without a Trace',2),
(NULL, 'Fysikbasserne',3),
(NULL, 'Helion',3),
(NULL, 'Twix',3),
(NULL, 'Unethical',3),
(NULL, 'Advance',3),
(NULL, 'Arctic Avengers',3),
(NULL, 'E V O L U T I O N',3),
(NULL, 'FOR THE ALLÎANCE',3),
(NULL, 'Insanity',3),
(NULL, 'Integrity',3),
(NULL, 'Oderant',3),
(NULL, 'P G',3),
(NULL, 'PMA',3),
(NULL, 'Revoke',3),
(NULL, 'stay hydrated',3),
(NULL, 'Sum optime',3),
(NULL, 'Team Sweden',3),
(NULL, 'Two Ghouls One Cup',3),
(NULL, 'Vous ne passerez pas',3),
(NULL, 'Øgma Tuatha',3),
(NULL, 'Адская Орда',3),
(NULL, 'Селфлесс',3),
(NULL, 'Чёрный Лотос',3),
(NULL, 'Crown',3),
(NULL, 'Distopia',3),
(NULL, 'FatSharkYes',3),
(NULL, 'Feed',3),
(NULL, 'Myst',3),
(NULL, 'Slack',3),
(NULL, 'Team Fight',3),
(NULL, 'The Haunted',3),
(NULL, 'Unicornz',3),
(NULL, 'В КОЛХОЗ ЗА ПЕТУХАМИ',3),
(NULL, 'THE MOVE',3),
(NULL, 'SSEN',3),
(NULL, 'Mørdor',3),
(NULL, 'one lesson per day',3),
(NULL, 'ddosed',3),
(NULL, 'hey im mvp',3),
(NULL, 'Still On Sargeras',3),
(NULL, 'ddosedx',3),
(NULL, 'Cyber Athletes',3),
(NULL, 'Gnomeland Security',3),
(NULL, 'ad hoc',3),
(NULL, 'slash spit',3),
(NULL, 'Suppy',3),
(NULL, 'Crimson Dragon',3),
(NULL, 'The Syndicate',3),
(NULL, 'Blur',3),
(NULL, 'tEh mOve',3),
(NULL, 'Cherry Pink',3),
(NULL, 'Honestly',3),
(NULL, 'Disney World',3),
(NULL, 'poptart corndoG',3),
(NULL, 'See Again Solitary',3),
(NULL, 'Infinity',3),
(NULL, 'BIG DAM',3),
(NULL, 'Ethical',3),
(NULL, 'BloodBoùnd',3),
(NULL, 'Show Me How',3),
(NULL, 'dog squad',3),
(NULL, 'Zandalari Bobsled Team',3),
(NULL, 'Goons Goonies',3),
(NULL, 'Legacy of the Alliance',3),
(NULL, 'Spiral Out',3),
(NULL, 'Melt',3),
(NULL, 'Last Attempt',3),
(NULL, 'Nolifer',3),
(NULL, 'RBG Hero',5),
(NULL, 'Medium',5),
(NULL, 'Nascent',5),
(NULL, 'M E R C I L E S S',5),
(NULL, 'Team Thougs',5),
(NULL, 'Verdict',5),
(NULL, 'CMG',5),
(NULL, 'Dishonorable Kill',5),
(NULL, 'Knights Who Say Yee',5),
(NULL, 'Restricted',5),
(NULL, 'Vile',5),
(NULL, 'Nemesis',5),
(NULL, 'Oasis',5),
(NULL, 'The Depraved',5),
(NULL, 'didnt ask',5),
(NULL, 'Epic Gamers',5),
(NULL, 'Essence',5),
(NULL, 'i love slicedbaka',5),
(NULL, 'Lights Oath',5),
(NULL, 'M Y T H I C C',5),
(NULL, 'Major Pain',5),
(NULL, 'Dads Against Vaping',5),
(NULL, 'No Skill',5),
(NULL, 'The Degenerates',5),
(NULL,'Boralus Yacht Club',5),
(NULL, 'Censored',5),
(NULL, 'Defenestrate',5),
(NULL, 'HATE DIVISION',5),
(NULL, 'hi',5),
(NULL, 'Ironsworn Regiment',5),
(NULL, 'is kinda like god',5),
(NULL, 'Temerity',5),
(NULL, 'The Pantheon NB',5),
(NULL, 'Vision',5),
(NULL, 'Baddies',5),
(NULL, 'Complexity Limit',5),
(NULL, 'Dark Clan of Fenris',5),
(NULL, 'Elite Horde',5),
(NULL, 'Makin a Bagel',5),
(NULL, 'Nimue',5),
(NULL, 'Ran Thru',5),
(NULL, 'Sin',5),
(NULL, 'VØDKA SØCIETY',5),
(NULL, 'Wizards and Monkeys',5),
(NULL, 'Is cute AF',5),
(NULL, 'Reckless Ambition',5),
(NULL, 'Solidarity Gaming',5),
(NULL, 'Spike Flail',5),
(NULL, 'Vexation',5),
(NULL, 'Hungry Wolves',5),
(NULL, 'Peel Team Six',5),
(NULL, 'Polaris',5),
(NULL, 'rest easy criter',5),
(NULL, 'Scripted',5),
(NULL, 'TAG',5),
(NULL, 'toXique',5),
(NULL, 'who are you talkin to',5),
(NULL, 'CRvillains',5),
(NULL, 'Decapodian',5),
(NULL, 'Fierce',5),
(NULL, 'Glad to see you',5),
(NULL, 'Impression',5),
(NULL, 'Nerd Rage',5),
(NULL, 'The Art of War',5),
(NULL, 'Wisdom',5);