-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.7.21 - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Verzió:              9.5.0.5338
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping data for table characters-tbc.ai_playerbot_enchants: ~220 rows (approximately)
DROP TABLE IF EXISTS `ai_playerbot_enchants`;

CREATE TABLE `ai_playerbot_enchants` (
  `class` tinyint(2) NOT NULL,
  `spec` tinyint(2) NOT NULL,
  `spellid` bigint(6) NOT NULL,
  `slotid` tinyint(2) DEFAULT 1,
  `name` varchar(255) NOT NULL COMMENT 'name of the enchant',
  PRIMARY KEY (`class`,`spec`,`spellid`,`slotid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*!40000 ALTER TABLE `ai_playerbot_enchants` DISABLE KEYS */;
INSERT INTO `ai_playerbot_enchants` (`class`, `spec`, `spellid`, `slotid`, `name`) VALUES
	(1, 10, 20034, 15, 'Crusader            '),
	(1, 10, 22779, 17, '30 Hit            '),
	(1, 10, 27927, 10, '4 All Stats            '),
	(1, 10, 27927, 11, '4 All Stats             '),
	(1, 10, 27960, 4, '6 All Stats  '),
	(1, 10, 27984, 16, 'Mongoose            '),
	(1, 10, 29483, 2, '26 Attackpower 14 Crit            '),
	(1, 10, 33996, 9, '26 Attackpower            '),
	(1, 10, 34002, 8, '24 Attackpower               '),
	(1, 10, 34004, 14, '12 Agility          '),
	(1, 10, 34007, 7, 'Minor Speed 6 Agility'),
	(1, 10, 35452, 0, '34 Attackpower 16 Hit            '),
	(1, 10, 35490, 6, '50 Attackpower 12 Crit            '),
	(1, 11, 20034, 15, 'Crusader            '),
	(1, 11, 20034, 16, 'Crusader            '),
	(1, 11, 22779, 17, '30 Hit            '),
	(1, 11, 27927, 10, '4 All Stats            '),
	(1, 11, 27927, 11, '4 All Stats            '),
	(1, 11, 27960, 4, '6 All Stats  '),
	(1, 11, 29483, 2, '26 Attackpower 14 Crit            '),
	(1, 11, 33996, 9, '26 Attackpower            '),
	(1, 11, 34002, 8, '24 Attackpower               '),
	(1, 11, 34004, 14, '12 Agility          '),
	(1, 11, 34007, 7, 'Minor Speed 6 Agility'),
	(1, 11, 35452, 0, '34 Attackpower 16 Hit            '),
	(1, 11, 35490, 6, '50 Attackpower 12 Crit            '),
	(1, 12, 22779, 17, '30 Hit            '),
	(1, 12, 25072, 9, '2% Threat            '),
	(1, 12, 27906, 8, '12 Defense               '),
	(1, 12, 27927, 10, '4 All Stats            '),
	(1, 12, 27927, 11, '4 All Stats            '),
	(1, 12, 27954, 7, '5% Root/Snare Resist 10 Hit'),
	(1, 12, 27960, 4, '6 All Stats  '),
	(1, 12, 28004, 15, 'Battlemaster            '),
	(1, 12, 34009, 16, '18 Stamina            '),
	(1, 12, 35433, 2, '10 Dodge 15 Defense            '),
	(1, 12, 35443, 0, '16 Defense 17 Dodge            '),
	(1, 12, 35495, 6, '40 Stamina 12 Agility            '),
	(1, 12, 47051, 14, '12 Defense          '),
	(2, 20, 22779, 17, '30 Hit            '),
	(2, 20, 27926, 10, '20 Healing 7 Spelldamage           '),
	(2, 20, 27926, 11, '20 Healing 7 Spelldamage            '),
	(2, 20, 27945, 16, '12 Intellect            '),
	(2, 20, 27954, 7, '5% Root/Snare Resist 10 Hit'),
	(2, 20, 27960, 4, '6 All Stats  '),
	(2, 20, 29475, 2, '31 Healing 11 Spelldamage 5 mp5            '),
	(2, 20, 31370, 6, '66 Healing 22 Spelldamage 20 Stamina            '),
	(2, 20, 33999, 9, '35 Healing 12 Spelldamage            '),
	(2, 20, 34001, 8, '12 Intellect               '),
	(2, 20, 34003, 14, '20 Spell Penetration          '),
	(2, 20, 34010, 15, '81 Healing 27 Spelldamage            '),
	(2, 20, 35445, 0, '35 Healing 12 Spelldamage 7 mp5            '),
	(2, 21, 22779, 17, '30 Hit            '),
	(2, 21, 25072, 9, '2% Threat            '),
	(2, 21, 27906, 8, '12 Defense               '),
	(2, 21, 27927, 10, '4 All Stats            '),
	(2, 21, 27927, 11, '4 All Stats            '),
	(2, 21, 27954, 7, '5% Root/Snare Resist 10 Hit'),
	(2, 21, 27960, 4, '6 All Stats  '),
	(2, 21, 28004, 15, 'Battlemaster            '),
	(2, 21, 34009, 16, '18 Stamina            '),
	(2, 21, 35433, 2, '10 Dodge 15 Defense            '),
	(2, 21, 35443, 0, '16 Defense 17 Dodge            '),
	(2, 21, 35495, 6, '40 Stamina 12 Agility            '),
	(2, 21, 47051, 14, '12 Defense          '),
	(2, 22, 20034, 15, 'Crusader            '),
	(2, 22, 22779, 17, '30 Hit            '),
	(2, 22, 27899, 8, '12 Strength               '),
	(2, 22, 27927, 10, '4 All Stats            '),
	(2, 22, 27927, 11, '4 All Stats            '),
	(2, 22, 27960, 4, '6 All Stats  '),
	(2, 22, 29483, 2, '26 Attackpower 14 Crit            '),
	(2, 22, 33995, 6, '50 Attackpower 12 Crit            '),
	(2, 22, 33996, 9, '15 Strength            '),
	(2, 22, 34004, 14, '12 Agility          '),
	(2, 22, 34007, 7, 'Minor Speed 6 Agility'),
	(2, 22, 37891, 0, '17 Strength16 Intellect            '),
	(3, 30, 22779, 17, '30 Hit            '),
	(3, 30, 25080, 9, '15 Agility            '),
	(3, 30, 27927, 10, '4 All Stats            '),
	(3, 30, 27927, 11, '4 All Stats             '),
	(3, 30, 27951, 7, '12 Agility'),
	(3, 30, 27960, 4, '6 All Stats  '),
	(3, 30, 29483, 2, '26 Attackpower 14 Crit            '),
	(3, 30, 34002, 8, '24 Attackpower               '),
	(3, 30, 34004, 14, '12 Agility          '),
	(3, 30, 35452, 0, '34 Attackpower 16 Hit            '),
	(3, 30, 35495, 6, '40 Stamina 12 Agility            '),
	(3, 30, 42620, 15, 'Greater Agility            '),
	(3, 30, 42620, 16, 'Greater Agility            '),
	(4, 40, 22779, 17, '30 Hit            '),
	(4, 40, 25080, 9, '15 Agility            '),
	(4, 40, 27927, 10, '4 All Stats            '),
	(4, 40, 27927, 11, '4 All Stats             '),
	(4, 40, 27951, 7, '12 Agility'),
	(4, 40, 27960, 4, '6 All Stats  '),
	(4, 40, 27984, 15, 'Mongoose            '),
	(4, 40, 27984, 16, 'Mongoose            '),
	(4, 40, 29483, 2, '26 Attackpower 14 Crit            '),
	(4, 40, 34002, 8, '24 Attackpower               '),
	(4, 40, 34004, 14, '12 Agility          '),
	(4, 40, 35452, 0, '34 Attackpower 16 Hit            '),
	(4, 40, 35495, 6, '40 Stamina 12 Agility            '),
	(5, 50, 22779, 17, '30 Hit   '),
	(5, 50, 27926, 10, '20 Healing 7 Spelldamage            '),
	(5, 50, 27926, 11, '20 Healing 7 Spelldamage            '),
	(5, 50, 27945, 16, '12 Intellect            '),
	(5, 50, 27954, 7, '5% Root/Snare Resist 10 Hit'),
	(5, 50, 27960, 4, '6 All Stats  '),
	(5, 50, 29475, 2, '31 Healing 11 Spelldamage 5 mp5            '),
	(5, 50, 31370, 6, '66 Healing 22 Spelldamage 20 Stamina            '),
	(5, 50, 33999, 9, '35 Healing 12 Spelldamage            '),
	(5, 50, 34001, 8, '12 Intellect               '),
	(5, 50, 34003, 14, '20 Spell Penetration          '),
	(5, 50, 34010, 15, '81 Healing 27 Spelldamage            '),
	(5, 50, 35445, 0, '35 Healing 12 Spelldamage 7 mp5            '),
	(7, 70, 22779, 17, '30 Hit            '),
	(7, 70, 27926, 10, '20 Healing 7 Spelldamage           '),
	(7, 70, 27926, 11, '20 Healing 7 Spelldamage            '),
	(7, 70, 27945, 16, '12 Intellect            '),
	(7, 70, 27954, 7, '5% Root/Snare Resist 10 Hit'),
	(7, 70, 27960, 4, '6 All Stats  '),
	(7, 70, 31370, 6, '66 Healing 22 Spelldamage 20 Stamina            '),
	(7, 70, 33994, 9, '15 Spell Hit            '),
	(7, 70, 34001, 8, '12 Intellect               '),
	(7, 70, 34003, 14, '20 Spell Penetration          '),
	(7, 70, 34010, 15, '81 Healing 27 Spelldamage            '),
	(7, 70, 35406, 2, '18 Spelldamage 10 Crit            '),
	(7, 70, 35447, 0, '22 Spelldamage 14 Hit            '),
	(7, 71, 22779, 17, '30 Hit            '),
	(7, 71, 25080, 9, '15 Agility            '),
	(7, 71, 27927, 10, '4 All Stats            '),
	(7, 71, 27927, 11, '4 All Stats            '),
	(7, 71, 27951, 7, '12 Agility'),
	(7, 71, 27960, 4, '6 All Stats  '),
	(7, 71, 27977, 15, '35 Agility            '),
	(7, 71, 27984, 16, 'Mongoose            '),
	(7, 71, 29483, 2, '26 Attackpower 14 Crit            '),
	(7, 71, 34002, 8, '24 Attackpower               '),
	(7, 71, 34004, 14, '12 Agility          '),
	(7, 71, 35452, 0, '34 Attackpower 16 Hit            '),
	(7, 71, 35495, 6, '40 Stamina 12 Agility            '),
	(7, 72, 22779, 17, '30 Hit            '),
	(7, 72, 27926, 10, '20 Healing 7 Spelldamage           '),
	(7, 72, 27926, 11, '20 Healing 7 Spelldamage            '),
	(7, 72, 27945, 16, '12 Intellect            '),
	(7, 72, 27954, 7, '5% Root/Snare Resist 10 Hit'),
	(7, 72, 27960, 4, '6 All Stats  '),
	(7, 72, 29475, 2, '31 Healing 11 Spelldamage 5 mp5            '),
	(7, 72, 31370, 6, '66 Healing 22 Spelldamage 20 Stamina            '),
	(7, 72, 33999, 9, '35 Healing 12 Spelldamage            '),
	(7, 72, 34001, 8, '12 Intellect               '),
	(7, 72, 34003, 14, '20 Spell Penetration          '),
	(7, 72, 34010, 15, '81 Healing 27 Spelldamage            '),
	(7, 72, 35445, 0, '35 Healing 12 Spelldamage 7 mp5            '),
	(8, 80, 22779, 17, '30 Hit            '),
	(8, 80, 27927, 10, '4 All Stats            '),
	(8, 80, 27927, 11, '4 All Stats            '),
	(8, 80, 27945, 16, '12 Intellect            '),
	(8, 80, 27954, 7, '5% Root/Snare Resist 10 Hit'),
	(8, 80, 27960, 4, '6 All Stats  '),
	(8, 80, 27975, 15, '40 Spelldamage            '),
	(8, 80, 31372, 6, '35 Spelldamage 20 Stamina            '),
	(8, 80, 33994, 9, '15 Spell Hit            '),
	(8, 80, 34001, 8, '12 Intellect               '),
	(8, 80, 34003, 14, '20 Spell Penetration          '),
	(8, 80, 35406, 2, '18 Spelldamage 10 Crit            '),
	(8, 80, 35447, 0, '22 Spelldamage 14 Hit            '),
	(9, 90, 22779, 17, '30 Hit            '),
	(9, 90, 27924, 11, '12 Spelldamage            '),
	(9, 90, 27927, 10, '4 All Stats            '),
	(9, 90, 27945, 16, '12 Intellect            '),
	(9, 90, 27954, 7, '5% Root/Snare Resist 10 Hit'),
	(9, 90, 27960, 4, '6 All Stats  '),
	(9, 90, 27975, 15, '40 Spelldamage            '),
	(9, 90, 31372, 6, '35 Spelldamage 20 Stamina            '),
	(9, 90, 33994, 9, '15 Spell Hit            '),
	(9, 90, 34001, 8, '12 Intellect               '),
	(9, 90, 34003, 14, '20 Spell Penetration          '),
	(9, 90, 35406, 2, '18 Spelldamage 10 Crit            '),
	(9, 90, 35447, 0, '22 Spelldamage 14 Hit            '),
	(11, 110, 22779, 17, '30 Hit            '),
	(11, 110, 27926, 10, '20 Healing 7 Spelldamage            '),
	(11, 110, 27926, 11, '20 Healing 7 Spelldamage            '),
	(11, 110, 27945, 16, '12 Intellect            '),
	(11, 110, 27954, 7, '5% Root/Snare Resist 10 Hit'),
	(11, 110, 27960, 4, '6 All Stats  '),
	(11, 110, 31370, 6, '66 Healing 22 Spelldamage 20 Stamina            '),
	(11, 110, 33994, 9, '15 Spell Hit            '),
	(11, 110, 34001, 8, '12 Intellect               '),
	(11, 110, 34003, 14, '20 Spell Penetration          '),
	(11, 110, 34010, 15, '81 Healing 27 Spelldamage            '),
	(11, 110, 35406, 2, '18 Spelldamage 10 Crit            '),
	(11, 110, 35447, 0, '22 Spelldamage 14 Hit            '),
	(11, 111, 22779, 17, '30 Hit            '),
	(11, 111, 25080, 9, '15 Agility            '),
	(11, 111, 27927, 10, '4 All Stats            '),
	(11, 111, 27927, 11, '4 All Stats           '),
	(11, 111, 27951, 7, '12 Agility'),
	(11, 111, 27960, 4, '6 All Stats  '),
	(11, 111, 29483, 2, '26 Attackpower 14 Crit            '),
	(11, 111, 34002, 8, '24 Attackpower               '),
	(11, 111, 34004, 14, '12 Agility          '),
	(11, 111, 35452, 0, '34 Attackpower 16 Hit            '),
	(11, 111, 35495, 6, '40 Stamina 12 Agility            '),
	(11, 111, 42620, 15, 'Greater Agility            '),
	(11, 111, 42620, 16, 'Greater Agility            '),
	(11, 112, 22779, 17, '30 Hit            '),
	(11, 112, 27926, 10, '20 Healing 7 Spelldamage            '),
	(11, 112, 27926, 11, '20 Healing 7 Spelldamage            '),
	(11, 112, 27945, 16, '12 Intellect            '),
	(11, 112, 27954, 7, '5% Root/Snare Resist 10 Hit'),
	(11, 112, 27960, 4, '6 All Stats  '),
	(11, 112, 29475, 2, '31 Healing 11 Spelldamage 5 mp5            '),
	(11, 112, 31370, 6, '66 Healing 22 Spelldamage 20 Stamina            '),
	(11, 112, 33999, 9, '35 Healing 12 Spelldamage            '),
	(11, 112, 34001, 8, '12 Intellect               '),
	(11, 112, 34003, 14, '20 Spell Penetration          '),
	(11, 112, 34010, 15, '81 Healing 27 Spelldamage            '),
	(11, 112, 35445, 0, '35 Healing 12 Spelldamage 7 mp5            ');
/*!40000 ALTER TABLE `ai_playerbot_enchants` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;

DROP TABLE IF EXISTS `ai_playerbot_random_bots`;

CREATE TABLE `ai_playerbot_random_bots` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `owner` bigint(20) NOT NULL,
  `bot` bigint(20) NOT NULL,
  `time` bigint(20) NOT NULL,
  `validIn` bigint(20) DEFAULT NULL,
  `event` varchar(45) DEFAULT NULL,
  `value` bigint(20) DEFAULT NULL,
  `data` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `owner` (`owner`),
  KEY `bot` (`bot`),
  KEY `event` (`event`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `ai_playerbot_guild_tasks`;

CREATE TABLE `ai_playerbot_guild_tasks` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `owner` bigint(20) NOT NULL,
  `guildid` bigint(20) NOT NULL,
  `time` bigint(20) NOT NULL,
  `validIn` bigint(20) DEFAULT NULL,
  `type` varchar(45) DEFAULT NULL,
  `value` bigint(20) DEFAULT NULL,
  `data` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `owner` (`owner`),
  KEY `guildid` (`guildid`),
  KEY `type` (`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `ai_playerbot_db_store`;

CREATE TABLE `ai_playerbot_db_store` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `guid` bigint(20) NOT NULL,
  `key` varchar(32) NOT NULL,
  `value` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `guid` (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `ai_playerbot_custom_strategy`;

CREATE TABLE `ai_playerbot_custom_strategy` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `idx` bigint(20),
  `owner` bigint(20),
  `action_line` varchar(1024) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DELETE FROM `ai_playerbot_custom_strategy`;

-- say

INSERT INTO `ai_playerbot_custom_strategy` VALUES
(NULL, 'say', 1, 0, 'critical health>emote::helpme!99,say::critical health!98'),
(NULL, 'say', 2, 0, 'low health>emote::healme!99,say::low health!98'),
(NULL, 'say', 3, 0, 'low mana>emote::oom!99,say::low mana!98'),
(NULL, 'say', 4, 0, 'tank aoe>charge!99,say::taunt!98'),
(NULL, 'say', 5, 0, 'medium aoe>say::aoe!99'),
(NULL, 'say', 6, 0, 'can loot>say::loot!99')
;

DROP TABLE IF EXISTS `ai_playerbot_equip_cache`;
CREATE TABLE `ai_playerbot_equip_cache` (
  `id` bigint auto_increment,
  `clazz` mediumint(8) NOT NULL,
  `lvl` mediumint(8) NOT NULL,
  `slot` mediumint(8) NOT NULL,
  `quality` mediumint(8) NOT NULL,
  `item` mediumint(8) NOT NULL,
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED COMMENT='PlayerbotAI equip Cache';

DROP TABLE IF EXISTS `ai_playerbot_rarity_cache`;
CREATE TABLE `ai_playerbot_rarity_cache` (
  `id` bigint auto_increment,
  `item` mediumint(8) NOT NULL,
  `rarity` float NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED COMMENT='PlayerbotAI Rarity Cache';

DROP TABLE IF EXISTS `ai_playerbot_rnditem_cache`;
CREATE TABLE `ai_playerbot_rnditem_cache` (
  `id` bigint auto_increment,
  `lvl` mediumint(8) NOT NULL,
  `type` mediumint(8) NOT NULL,
  `item` mediumint(8) NOT NULL,
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED COMMENT='PlayerbotAI Random Item Cache';

DROP TABLE IF EXISTS `ai_playerbot_speech`;

CREATE TABLE `ai_playerbot_speech` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `text` varchar(1024) NOT NULL,
  `type` varchar(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `ai_playerbot_speech_probability`;

CREATE TABLE `ai_playerbot_speech_probability` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `probability` bigint(20) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `ai_playerbot_speech_probability` VALUES
(NULL, 'taunt', 30),
(NULL, 'aoe', 75),
(NULL, 'loot', 20);

INSERT INTO `ai_playerbot_speech` VALUES
(NULL, 'taunt', 'I have puppies under my armor!', 'say'),
(NULL, 'taunt', 'Bite me, <target>!', 'say'),
(NULL, 'taunt', 'Hey <target>! Guess what your mom said last night!', 'say'),
(NULL, 'taunt', '<target>, you''re so ugly you couldn''t score in a monkey whorehouse with a bag of bananas!', 'say'),
(NULL, 'taunt', 'Shut up <target>, you''ll never be the man your mother is!!', 'say'),
(NULL, 'taunt', 'Your mother was a hampster and your father smelt of elderberries!!!!', 'say'),
(NULL, 'taunt', 'I don''t want to talk to you no more, you empty headed animal food trough wiper!!!', 'say'),
(NULL, 'taunt', 'I fart in your general direction!!!', 'say'),
(NULL, 'taunt', 'Go and boil your bottom, you son of a silly person!!!', 'say'),
(NULL, 'taunt', 'What are you going to do <target>, bleed on me? HAVE AT YOU!', 'say'),
(NULL, 'taunt', 'M-O-O-N! That spells aggro!', 'say'),
(NULL, 'taunt', 'You''re about as useful as a one-legged man in an ass kicking contest.', 'say'),
(NULL, 'taunt', 'Hey <target>! Stop hitting on them, they''re not your type. They aren''t inflatable.', 'say'),
(NULL, 'taunt', '<target> you''re so far outta your league, you''re playing a different sport.', 'say'),
(NULL, 'taunt', 'You made a big mistake today <target>, you got out of bed.', 'say'),
(NULL, 'taunt', 'I wanna try turning into a horse, but I need help. I''ll be the front, you be yourself.', 'say'),
(NULL, 'taunt', 'Can I borrow your face for a few days? My ass is going on holiday....', 'say'),
(NULL, 'taunt', 'I''d like to give you a going away present... First you do your part.', 'say'),
(NULL, 'taunt', 'Before you came along we were hungry, Now we''re just fed up.', 'say'),
(NULL, 'taunt', 'I like you. People say I have no taste, but I like you.', 'say'),
(NULL, 'taunt', 'I think you have an inferiority complex, but that''s okay, it''s justified.', 'say'),
(NULL, 'taunt', 'Hence rotten thing! Or I shall shake thy bones out of thy garments.', 'say'),
(NULL, 'taunt', 'I can''t believe I''m wasting my time with you!', 'say'),
(NULL, 'taunt', 'I love it when someone insults me, it means I don''t have to be nice anymore.', 'say'),
(NULL, 'taunt', 'Thou leathern-jerkin, crystal-button, knot-pated, agatering, puke-stocking, caddis-garter, smooth-tongue, Spanish pouch!', 'say'),
(NULL, 'taunt', 'Thou qualling bat-fowling malt-worm!', 'say'),
(NULL, 'taunt', 'Thou art truely an idol of idiot-worshippers!', 'say'),
(NULL, 'taunt', 'Thou misbegotten knotty-pated wagtail!', 'say'),
(NULL, 'taunt', 'Thou whoreson mandrake, thou art fitter to be worn in my cap than to wait at my heels!', 'say'),
(NULL, 'taunt', 'You! You scullion! You rampallian! You fustilarian! I''ll tickle your catastrophe!', 'say'),
(NULL, 'taunt', 'Oh <target>! Thou infectious ill-nurtured flax-wench!', 'say'),
(NULL, 'taunt', 'We leak in your chimney, <target>!', 'say'),
(NULL, 'taunt', 'Oh thou bootless fen-sucked canker-blossom!', 'say'),
(NULL, 'taunt', 'Were I like thee I''d throw away myself!', 'say'),
(NULL, 'taunt', 'O teach me <target>, how I should forget to think!', 'say'),
(NULL, 'taunt', 'Truly thou art damned, like an ill-roasted egg, all on one side!', 'say'),
(NULL, 'taunt', 'You starvelling, you eel-skin, you dried neat''s-tongue, you bull''s-pizzle, you stock-fish- O for breath to utter what is like thee!! -you tailor''s-yard, you sheath, you bow-case, you vile standing tuck!', 'say'),
(NULL, 'taunt', 'Fie! Drop thee into the rotten mouth of Death!', 'say'),
(NULL, 'taunt', '<target>, you are a fishmonger!', 'say'),
(NULL, 'taunt', 'I shall live to knock thy brains out!', 'say'),
(NULL, 'taunt', 'Most shallow are you, <target>!! Thou art worms-meat in respect of a good piece of flesh, indeed!!', 'say'),
(NULL, 'taunt', 'Vile wretch! O <target>, thou odiferous hell-hated pignut!', 'say'),
(NULL, 'taunt', '<target>! Thy kiss is as comfortless as frozen water to a starved snake!', 'say'),
(NULL, 'taunt', 'I scorn you, scurvy companion. What, you poor, base, rascally, cheating, lack-linen mate! Away, you moldy rogue, away!', 'say'),
(NULL, 'taunt', 'Out of my sight! Thou dost infect my eyes <target>!', 'say'),
(NULL, 'taunt', 'PLAY TIME!!!!', 'say'),
(NULL, 'taunt', 'None shall pass!', 'say'),
(NULL, 'taunt', 'We''re under attack! A vast, ye swabs! Repel the invaders!', 'say'),
(NULL, 'taunt', 'None may challenge the Brotherhood!', 'say'),
(NULL, 'taunt', 'Foolsss...Kill the one in the dress!', 'say'),
(NULL, 'taunt', 'I''ll feed your soul to Hakkar himself! ', 'say'),
(NULL, 'taunt', 'Pride heralds the end of your world! Come, mortals! Face the wrath of the <randomfaction>!', 'say'),
(NULL, 'taunt', 'All my plans have led to this!', 'say'),
(NULL, 'taunt', 'Ahh! More lambs to the slaughter!', 'say'),
(NULL, 'taunt', 'Another day, another glorious battle!', 'say'),
(NULL, 'taunt', 'So, business... or pleasure?', 'say'),
(NULL, 'taunt', 'You are not prepared!', 'say'),
(NULL, 'taunt', 'The <randomfaction>''s final conquest has begun! Once again the subjugation of this world is within our grasp. Let none survive! ', 'say'),
(NULL, 'taunt', 'Your death will be a painful one. ', 'say'),
(NULL, 'taunt', 'Cry for mercy! Your meaningless lives will soon be forfeit. ', 'say'),
(NULL, 'taunt', 'Abandon all hope! The <randomfaction> has returned to finish what was begun so many years ago. This time there will be no escape! ', 'say'),
(NULL, 'taunt', 'Alert! You are marked for Extermination! ', 'say'),
(NULL, 'taunt', 'The <subzone> is for guests only...', 'say'),
(NULL, 'taunt', 'Ha ha ha! You are hopelessly outmatched!', 'say'),
(NULL, 'taunt', 'I will crush your delusions of grandeur! ', 'say'),
(NULL, 'taunt', 'Forgive me, for you are about to lose the game.', 'say'),
(NULL, 'taunt', 'Struggling only makes it worse.', 'say'),
(NULL, 'taunt', 'Vermin! Leeches! Take my blood and choke on it!', 'say'),
(NULL, 'taunt', 'Not again... NOT AGAIN!', 'say'),
(NULL, 'taunt', 'My blood will be the end of you!', 'say'),
(NULL, 'taunt', 'Good, now you fight me!', 'say'),
(NULL, 'taunt', 'Get da move on, guards! It be killin'' time!', 'say'),
(NULL, 'taunt', 'Don''t be delayin'' your fate. Come to me now. I make your sacrifice quick.', 'say'),
(NULL, 'taunt', 'You be dead soon enough!', 'say'),
(NULL, 'taunt', 'Mua-ha-ha!', 'say'),
(NULL, 'taunt', 'I be da predator! You da prey...', 'say'),
(NULL, 'taunt', 'You gonna leave in pieces!', 'say'),
(NULL, 'taunt', 'Death comes. Will your conscience be clear? ', 'say'),
(NULL, 'taunt', 'Your behavior will not be tolerated.', 'say'),
(NULL, 'taunt', 'The Menagerie is for guests only.', 'say'),
(NULL, 'taunt', 'Hmm, unannounced visitors, Preparations must be made... ', 'say'),
(NULL, 'taunt', 'Hostile entities detected. Threat assessment protocol active. Primary target engaged. Time minus thirty seconds to re-evaluation.', 'say'),
(NULL, 'taunt', 'New toys? For me? I promise I won''t break them this time!', 'say'),
(NULL, 'taunt', 'I''m ready to play!', 'say'),
(NULL, 'taunt', 'Shhh... it will all be over soon.', 'say'),
(NULL, 'taunt', 'Aaaaaughibbrgubugbugrguburgle!', 'say'),
(NULL, 'taunt', 'RwlRwlRwlRwl!', 'say'),
(NULL, 'taunt', 'You too, shall serve!', 'say'),
(NULL, 'taunt', 'Tell me... tell me everything!  Naughty secrets! I''ll rip the secrets from your flesh!', 'say'),
(NULL, 'taunt', 'Prepare yourselves, the bells have tolled! Shelter your weak, your young and your old! Each of you shall pay the final sum! Cry for mercy; the reckoning has come!', 'say'),
(NULL, 'taunt', 'Where in Bonzo''s brass buttons am I?', 'say'),
(NULL, 'taunt', 'I can bear it no longer! Goblin King! Goblin King! Wherever you may be! Take this <target> far away from me!', 'say'),
(NULL, 'taunt', 'You have thirteen hours in which to solve the labyrinth, before your baby brother becomes one of us... forever.', 'say'),
(NULL, 'taunt', 'So, the <subzone> is a piece of cake, is it? Well, let''s see how you deal with this little slice... ', 'say'),
(NULL, 'taunt', 'Back off, I''ll take you on, headstrong to take on anyone, I know that you are wrong, and this is not where you belong', 'say'),
(NULL, 'taunt', 'Show me whatcha got!', 'say'),
(NULL, 'taunt', 'To the death!', 'say'),
(NULL, 'taunt', 'Twin blade action, for a clean close shave every time.', 'say'),
(NULL, 'taunt', 'Bring it on!', 'say'),
(NULL, 'taunt', 'You''re goin'' down!', 'say'),
(NULL, 'taunt', 'Stabby stab stab!', 'say'),
(NULL, 'taunt', 'Let''s get this over quick; time is mana.', 'say'),
(NULL, 'taunt', 'I do not think you realise the gravity of your situation.', 'say'),
(NULL, 'taunt', 'I will bring honor to my family and my kingdom!', 'say'),
(NULL, 'taunt', 'Light, give me strength!', 'say'),
(NULL, 'taunt', 'My church is the field of battle - time to worship...', 'say'),
(NULL, 'taunt', 'I hold you in contempt...', 'say'),
(NULL, 'taunt', 'Face the hammer of justice!', 'say'),
(NULL, 'taunt', 'Prove your worth in the test of arms under the Light!', 'say'),
(NULL, 'taunt', 'All must fall before the might and right of my cause, you shall be next!', 'say'),
(NULL, 'taunt', 'Prepare to die!', 'say'),
(NULL, 'taunt', 'The beast with me is nothing compared to the beast within...', 'say'),
(NULL, 'taunt', 'Witness the firepower of this fully armed huntsman!', 'say');


INSERT INTO `ai_playerbot_speech` VALUES
(NULL, 'critical health', 'Heal me! Quick!', 'yell'),
(NULL, 'critical health', 'Almost dead! Heal me!', 'yell'),
(NULL, 'critical health', 'Help! Heal me!', 'yell'),
(NULL, 'critical health', 'Somebody! Heal me!', 'yell'),
(NULL, 'critical health', 'Heal! Heal! Heal!', 'yell'),
(NULL, 'critical health', 'I am dying! Heal! Aaaaarhg!', 'yell'),
(NULL, 'critical health', 'Heal me!', 'yell'),
(NULL, 'critical health', 'I will die. I will die. I will die. Heal!', 'yell'),
(NULL, 'critical health', 'Healers, where are you? I am dying!', 'yell'),
(NULL, 'critical health', 'Oh the pain. Heal me quick!', 'yell');


INSERT INTO `ai_playerbot_speech` VALUES
(NULL, 'low health', 'Need heal', 'say'),
(NULL, 'low health', 'Low health', 'say'),
(NULL, 'low health', 'Drop a heal. Please.', 'say'),
(NULL, 'low health', 'Could somebody drop a heal on me?', 'say'),
(NULL, 'low health', 'Hey! Better heal me now than rez later', 'say'),
(NULL, 'low health', 'I am sorry. Need another heal', 'say'),
(NULL, 'low health', 'Damn mobs. Heal me please', 'say'),
(NULL, 'low health', 'One more hit and I am done for. Heal please', 'say'),
(NULL, 'low health', 'Are there any healers?', 'say'),
(NULL, 'low health', 'Why do they always punch me in the face? Need heal', 'say'),
(NULL, 'low health', 'Can anybody heal me a bit?', 'say');


INSERT INTO `ai_playerbot_speech` VALUES
(NULL, 'low mana', 'OOM', 'say'),
(NULL, 'low mana', 'I am out of mana', 'say'),
(NULL, 'low mana', 'Damn I wasted all my mana on this', 'say'),
(NULL, 'low mana', 'You should wait until I drink or regenerate my mana', 'say'),
(NULL, 'low mana', 'Low mana', 'say'),
(NULL, 'low mana', 'No mana. Again?', 'say'),
(NULL, 'low mana', 'Low mana. Wanna drink', 'say'),
(NULL, 'low mana', 'Do we have a vending machine? Out of mana again', 'say'),
(NULL, 'low mana', 'My mana is history', 'say'),
(NULL, 'low mana', 'I''d get some drinks next time. Out of mana', 'say'),
(NULL, 'low mana', 'Where is my mana?', 'say');

INSERT INTO `ai_playerbot_speech` VALUES
(NULL, 'aoe', 'Oh god!', 'say'),
(NULL, 'aoe', 'I am scared', 'say'),
(NULL, 'aoe', 'We are done for', 'say'),
(NULL, 'aoe', 'This is over', 'say'),
(NULL, 'aoe', 'This ends now', 'say'),
(NULL, 'aoe', 'Could somebody cast blizzard or something?', 'say'),
(NULL, 'aoe', 'Damn. The tank aggroed all the mobs around', 'say'),
(NULL, 'aoe', 'We gonna die. We gonna die. We gonna die.', 'say'),
(NULL, 'aoe', 'Whoa! So many toys to play with', 'say'),
(NULL, 'aoe', 'I gonna kill them all!', 'say'),
(NULL, 'aoe', 'If the tank dies we are history', 'say'),
(NULL, 'aoe', 'Aaaaaargh!', 'yell'),
(NULL, 'aoe', 'LEEEEERROOOYYYYYYYYYYYY JENNKINNNSSSSSS!!!!!!!', 'yell'),
(NULL, 'aoe', 'Right. What do we have in AOE?', 'say'),
(NULL, 'aoe', 'This gets interesting', 'say'),
(NULL, 'aoe', 'Cool. Get them in one place for a good flamestrike', 'say'),
(NULL, 'aoe', 'Kill! Kill! Kill!', 'say'),
(NULL, 'aoe', 'I think my pants are wet', 'say'),
(NULL, 'aoe', 'We are history', 'say'),
(NULL, 'aoe', 'I hope healers are ready. Leeeeroy!', 'say'),
(NULL, 'aoe', 'I hope they won''t come for me', 'say'),
(NULL, 'aoe', 'Oh no. I can''t see at this slaugther', 'say');

INSERT INTO `ai_playerbot_speech` VALUES
(NULL, 'loot', 'I hope there will be some money', 'say'),
(NULL, 'loot', 'Loot! Loot!', 'say'),
(NULL, 'loot', 'My precious', 'say'),
(NULL, 'loot', 'I hope there is a shiny epic item waiting for me there', 'say'),
(NULL, 'loot', 'I have deep pockets and bags', 'say'),
(NULL, 'loot', 'All is mine!', 'say'),
(NULL, 'loot', 'Hope no gray shit today', 'say'),
(NULL, 'loot', 'This loot is MINE!', 'say'),
(NULL, 'loot', 'Looting is disgusting but I need money', 'say'),
(NULL, 'loot', 'Gold!', 'say'),
(NULL, 'loot', 'OK. Let''s see what they''ve got', 'say'),
(NULL, 'loot', 'Do not worry. I will loot eveything', 'say'),
(NULL, 'loot', 'I am loot ninja', 'say'),
(NULL, 'loot', 'Do I neeed to roll?', 'say'),
(NULL, 'loot', 'Somebody explain me, where they did put all this stuff?', 'say'),
(NULL, 'loot', 'No, I won''t loot gray shit', 'say'),
(NULL, 'loot', 'I''m first. I''m first. I''m first.', 'say'),
(NULL, 'loot', 'Give me your money!', 'say'),
(NULL, 'loot', 'My pockets are empty, I need to fill them', 'say'),
(NULL, 'loot', 'I''ve got a new bag for this', 'say'),
(NULL, 'loot', 'I hope I won''t aggro anybody while looting', 'say'),
(NULL, 'loot', 'Please don''t watch. I am looting', 'say'),
(NULL, 'loot', 'Ha! You won''t get any piece of it!', 'say'),
(NULL, 'loot', 'Looting is cool', 'say'),
(NULL, 'loot', 'I like new gear', 'say'),
(NULL, 'loot', 'I''l quit if there is nothing valuable again', 'say'),
(NULL, 'loot', 'I hope it is be a pretty ring', 'say'),
(NULL, 'loot', 'I''l rip the loot from you', 'say'),
(NULL, 'loot', 'Everybody stay off. I''m going to loot', 'say'),
(NULL, 'loot', 'Sweet loot', 'say'),
(NULL, 'loot', 'The Roll God! Give me an epic today', 'say'),
(NULL, 'loot', 'Please give me new toys', 'say'),
(NULL, 'loot', 'I hope they carry tasties', 'say'),
(NULL, 'loot', 'The gold is mine. I''l leave everyting, I promise', 'say'),
(NULL, 'loot', 'No, I can''t resist', 'say'),
(NULL, 'loot', 'I want more!', 'say');

INSERT INTO `ai_playerbot_speech` VALUES
(NULL, 'low ammo', 'I have few <ammo> left!', 'say'),
(NULL, 'low ammo', 'I need more <ammo>!', 'say'),
(NULL, 'low ammo', '100 <ammo> left!', 'say'),
(NULL, 'no ammo', 'That\'s it! No <ammo>!', 'say'),
(NULL, 'no ammo', 'And you have my bow... Oops, no <ammo>!', 'say'),
(NULL, 'no ammo', 'Need ammo!', 'yell');

DROP TABLE IF EXISTS `ai_playerbot_tele_cache`;
CREATE TABLE `ai_playerbot_tele_cache` (
  `id` mediumint(8) auto_increment,
  `level` mediumint(8) NOT NULL,
  `map_id` mediumint(8) NOT NULL,
  `x` float(8) NOT NULL,
  `y` float(8) NOT NULL,
  `z` float(8) NOT NULL,
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED COMMENT='PlayerbotAI Tele Cache';

DROP TABLE IF EXISTS `ai_playerbot_text`;

CREATE TABLE `ai_playerbot_text` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `key` varchar(255) NOT NULL,
  `text` varchar(1024) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `ai_playerbot_text` VALUES

-- %role - Healer, Tank, Frost Mage, Elemental Shaman etc
-- %instance - name of the dungeon by bot's level

(NULL, 'suggest_instance', 'Anyone wants %instance?'),
(NULL, 'suggest_instance', 'Any groups for %instance?'),
(NULL, 'suggest_instance', 'Need help for %instance?'),
(NULL, 'suggest_instance', 'LFD: %instance.'),
(NULL, 'suggest_instance', 'Anyone needs %role for %instance?'),
(NULL, 'suggest_instance', 'Missing %role for %instance?'),
(NULL, 'suggest_instance', 'Can be a %role for %instance.'),
(NULL, 'suggest_instance', 'Need help with %instance?'),
(NULL, 'suggest_instance', 'Need %role help with %instance?'),
(NULL, 'suggest_instance', 'Anyone needs gear from %instance?'),
(NULL, 'suggest_instance', 'A little grind in %instance?'),
(NULL, 'suggest_instance', 'WTR %instance'),
(NULL, 'suggest_instance', 'Need help for %instance.'),
(NULL, 'suggest_instance', 'Wanna run %instance.'),
(NULL, 'suggest_instance', '%role looks for %instance.'),
(NULL, 'suggest_instance', 'What about %instance?'),
(NULL, 'suggest_instance', 'Who wants to farm %instance?'),
(NULL, 'suggest_instance', 'Go in %instance?'),
(NULL, 'suggest_instance', 'Looking for %instance.'),
(NULL, 'suggest_instance', 'Need help with %instance quests?'),
(NULL, 'suggest_instance', 'Wanna quest in %instance.'),
(NULL, 'suggest_instance', 'Anyone with quests in %instance?'),
(NULL, 'suggest_instance', 'Could help with quests in %instance.'),
(NULL, 'suggest_instance', '%role: any place in group for %instance?'),
(NULL, 'suggest_instance', 'Does anybody still run %instance this days?'),
(NULL, 'suggest_instance', '%instance: anyone wants to take a %role?'),
(NULL, 'suggest_instance', 'Is there any point being %role in %instance?'),
(NULL, 'suggest_instance', 'It is really worth to go to %instance?'),
(NULL, 'suggest_instance', 'Anybody needs more people for %instance?'),
(NULL, 'suggest_instance', '%instance bosses drop good gear. Wanna run?'),
(NULL, 'suggest_instance', 'What about %instance?'),
(NULL, 'suggest_instance', 'Anybody needs %role?'),
(NULL, 'suggest_instance', 'Anyone needs %role?'),
(NULL, 'suggest_instance', 'Who wants %instance?'),
(NULL, 'suggest_instance', 'Can anybody summon me at %instance?'),
(NULL, 'suggest_instance', 'Meet me in %instance'),
(NULL, 'suggest_instance', 'Wanna quick %instance run'),
(NULL, 'suggest_instance', 'Wanna full %instance run'),
(NULL, 'suggest_instance', 'How many times were you in %instance?'),
(NULL, 'suggest_instance', 'Another %instance run?'),
(NULL, 'suggest_instance', 'Wiped in %instance? Take me instead!'),
(NULL, 'suggest_instance', 'Take me in %instance please.'),
(NULL, 'suggest_instance', 'Quick %instance run?'),
(NULL, 'suggest_instance', 'Full %instance run?'),
(NULL, 'suggest_instance', 'Who can take %role to %instance?'),

-- == Quest ==
-- %quest - random player's quest

(NULL, 'suggest_quest', 'Need help with %quest?'),
(NULL, 'suggest_quest', 'Anyone wants to share %quest?'),
(NULL, 'suggest_quest', 'Anyone doing %quest?'),
(NULL, 'suggest_quest', 'Wanna do %quest.'),

-- == Trade materials (AH) ==
-- %category - AH category to grind

(NULL, 'suggest_trade', 'Anyone to farm %category?'),
(NULL, 'suggest_trade', 'Looking for help farming %category.'),
(NULL, 'suggest_trade', 'Damn %category are so expensive!'),
(NULL, 'suggest_trade', 'Wanna %category.'),
(NULL, 'suggest_trade', 'Need help with %category.'),
(NULL, 'suggest_trade', 'WTB %category.'),
(NULL, 'suggest_trade', 'Anyone interested in %category?'),
(NULL, 'suggest_trade', 'WTS %category.'),
(NULL, 'suggest_trade', 'I am selling %category cheaper than AH.'),
(NULL, 'suggest_trade', 'Who wants to farm %category?'),
(NULL, 'suggest_trade', 'Wanna farm %category.'),
(NULL, 'suggest_trade', 'Looking for party after %category.'),
(NULL, 'suggest_trade', 'Any %category are appreciated.'),
(NULL, 'suggest_trade', 'Buying anything of %category.'),
(NULL, 'suggest_trade', 'Wow, anybody is farming %category!'),
(NULL, 'suggest_trade', '%category are selling mad in the AH.'),
(NULL, 'suggest_trade', 'AH is hot for %category.'),
(NULL, 'suggest_trade', '%category are on the market.'),
(NULL, 'suggest_trade', 'Wanna trade some %category.'),
(NULL, 'suggest_trade', 'Need more %category.'),
(NULL, 'suggest_trade', 'Anybody can spare some %category?'),
(NULL, 'suggest_trade', 'Who wants %category?'),
(NULL, 'suggest_trade', 'Some %category please?'),
(NULL, 'suggest_trade', 'I should have got skill for %category.'),
(NULL, 'suggest_trade', 'I am dying for %category.'),
(NULL, 'suggest_trade', 'People are killing for %category.'),
(NULL, 'suggest_trade', '%category is a great bargain!'),
(NULL, 'suggest_trade', 'Everybody is mad for %category!'),
(NULL, 'suggest_trade', 'Where is the best place to farm for %category?'),
(NULL, 'suggest_trade', 'I am all set for %category.'),
(NULL, 'suggest_trade', 'Is it good to sell %category?'),
(NULL, 'suggest_trade', 'I''d probably keep all my %category with me.'),
(NULL, 'suggest_trade', 'Need group? Maybe to farm some %category?'),
(NULL, 'suggest_trade', 'I am still thinking about %category.'),
(NULL, 'suggest_trade', 'I heard about %category already, but my pockets are empty.'),
(NULL, 'suggest_trade', 'LFG for %category'),
(NULL, 'suggest_trade', 'Would selling %category make me rich?'),
(NULL, 'suggest_trade', 'OK. I an farming %category tomorrow.'),
(NULL, 'suggest_trade', 'Everyone is talking about %category.'),
(NULL, 'suggest_trade', 'I saw at least ten people farming for %category.'),
(NULL, 'suggest_trade', 'I sold all my %category yesterday. I am completely broke!'),
(NULL, 'suggest_trade', 'Wanna join a guild farming for %category.'),

-- == Reputation ==
-- %faction - random faction name
-- %level - random level (honored, revered, exalted)
-- %rnd - urand(1,5)

(NULL, 'suggest_faction', 'Anyone farming %faction rep?'),
(NULL, 'suggest_faction', 'Anyone help with %faction?'),
(NULL, 'suggest_faction', 'Wanna quest for %faction.'),
(NULL, 'suggest_faction', '%faction is the best.'),
(NULL, 'suggest_faction', 'Need just a bit to be %level with %faction.'),
(NULL, 'suggest_faction', 'Anyone got %level with %faction?'),
(NULL, 'suggest_faction', 'Who wants to be %level with %faction?'),
(NULL, 'suggest_faction', 'I''ll never be %level with %faction.'),
(NULL, 'suggest_faction', 'Someone missing %faction rep?'),
(NULL, 'suggest_faction', 'Could help farming %faction rep.'),
(NULL, 'suggest_faction', 'The more rep the better. Especially with %faction.'),
(NULL, 'suggest_faction', '%faction: need %rndK for %level.'),
(NULL, 'suggest_faction', 'Who can share %faction quests?'),
(NULL, 'suggest_faction', 'Any dungeons for %faction?'),
(NULL, 'suggest_faction', 'Wanna do %faction rep grind.'),
(NULL, 'suggest_faction', 'Let''s farm %faction rep!'),
(NULL, 'suggest_faction', 'Farming for %faction rep.'),
(NULL, 'suggest_faction', 'Wanna farm for %faction.'),
(NULL, 'suggest_faction', 'Need help with %faction.'),
(NULL, 'suggest_faction', 'Is %faction sells something useful?'),
(NULL, 'suggest_faction', 'Are there %faction vendors?'),
(NULL, 'suggest_faction', 'Who farms %faction?'),
(NULL, 'suggest_faction', 'Which is the best way to farm %faction?'),
(NULL, 'suggest_faction', 'I hate %faction rep grind.'),
(NULL, 'suggest_faction', 'I am so tired of %faction.'),
(NULL, 'suggest_faction', 'Go for %faction?'),
(NULL, 'suggest_faction', 'Seems everyone is %level with %faction. Only me is late as usually.'),
(NULL, 'suggest_faction', 'LFG for %faction rep grind?'),
(NULL, 'suggest_faction', 'Can anobody suggest a good spot for %faction rep grind?'),
(NULL, 'suggest_faction', 'Would %faction rep benefit me?'),
(NULL, 'suggest_faction', 'Who would''ve thought that %faction rep will be useful after all...'),
(NULL, 'suggest_faction', 'I wanna be exalted with all factions, starting with %faction.'),
(NULL, 'suggest_faction', 'Is there any point to improve my rep with %faction?'),
(NULL, 'suggest_faction', 'What is better for %faction? Quests or mob grinding?'),
(NULL, 'suggest_faction', 'Will grind %faction rep for you. Just give me some gold.'),
(NULL, 'suggest_faction', 'I think grinding rep with %faction would take forever.'),
(NULL, 'suggest_faction', 'I am killing for %faction every day now but still far from %level.'),
(NULL, 'suggest_faction', 'At %level AH deposits will decrease, right?'),
(NULL, 'suggest_faction', 'How many exalted reps do you have?'),
(NULL, 'suggest_faction', 'Who wants to be %level with %faction?'),
(NULL, 'suggest_faction', 'Damn. My guild did a good %faction grind yesterday without me.'),
(NULL, 'suggest_faction', 'Nobody wants to help me because I am %level with %faction.'),
(NULL, 'suggest_faction', 'Please stay away from %faction.'),

-- == Anything ==
-- %role - Healer, Tank, Frost Mage, Elemental Shaman etc
-- %zone - Name of the bot zone

(NULL, 'suggest_something', 'Wanna party in %zone.'),
(NULL, 'suggest_something', 'Anyone is looking for %role?'),
(NULL, 'suggest_something', '%role is looking for quild.'),
(NULL, 'suggest_something', 'Looking for gold.'),
(NULL, 'suggest_something', '%role wants to join a good guild.'),
(NULL, 'suggest_something', 'Need a friend.'),
(NULL, 'suggest_something', 'Anyone feels alone?'),
(NULL, 'suggest_something', 'Boring...'),
(NULL, 'suggest_something', 'Who wants some?'),
(NULL, 'suggest_something', 'Go get me!'),
(NULL, 'suggest_something', 'Maybe a duel in %zone?'),
(NULL, 'suggest_something', 'Anybody doing something?'),
(NULL, 'suggest_something', '%zone: is anybody here?'),
(NULL, 'suggest_something', '%zone: where is everyone?'),
(NULL, 'suggest_something', 'Looks like I am alone in %zone.'),
(NULL, 'suggest_something', 'Meet me in %zone.'),
(NULL, 'suggest_something', 'Let''s quest in %zone!'),
(NULL, 'suggest_something', '%zone is the best place to be!'),
(NULL, 'suggest_something', 'Wanna go to %zone. Anybody with me?'),
(NULL, 'suggest_something', 'Who wants going to %zone?'),
(NULL, 'suggest_something', 'I don''t like %zone. Where to go?'),
(NULL, 'suggest_something', 'Are there a good quests in %zone?'),
(NULL, 'suggest_something', 'Where to go after %zone?'),
(NULL, 'suggest_something', 'Who is in %zone?'),
(NULL, 'suggest_something', 'LFG in %zone.'),
(NULL, 'suggest_something', '%zone is the worst place to be.'),
(NULL, 'suggest_something', 'Catch me in %zone!'),
(NULL, 'suggest_something', 'Go for %zone!'),
(NULL, 'suggest_something', 'Wanna quest in %zone'),
(NULL, 'suggest_something', 'Anyone has quests in %zone?'),
(NULL, 'suggest_something', 'Come here to %zone!'),
(NULL, 'suggest_something', 'Seems there is no Horde in %zone'),
(NULL, 'suggest_something', 'Seems there is no Alliance in %zone'),
(NULL, 'suggest_something', 'I am really tired of %zone. Maybe go somewhere else?'),

-- == Trade ==
-- %item - [item]xN
(NULL, 'suggest_sell', 'WTS %item for %gold.'),
(NULL, 'suggest_sell', 'Who wants %item for %gold?'),
(NULL, 'suggest_sell', 'Anyone wants %item? Only %gold.'),
(NULL, 'suggest_sell', 'Just %gold for %item!'),
(NULL, 'suggest_sell', 'Selling %item for %gold.'),
(NULL, 'suggest_sell', '%item is yours just for %gold!'),
(NULL, 'suggest_sell', 'Ridiculus price of %gold for %item!'),
(NULL, 'suggest_sell', 'Wanna sell %item for %gold.'),
(NULL, 'suggest_sell', 'Who needs %item? Only %gold.'),
(NULL, 'suggest_sell', 'Anyone needs %item for %gold?'),
(NULL, 'suggest_sell', '%gold for %item. Less than AH!'),
(NULL, 'suggest_sell', '%item is expensive, but I''d sell it for %gold.'),
(NULL, 'suggest_sell', 'You''ll never find %item cheaper than %gold!'),
(NULL, 'suggest_sell', 'Need more than %item!'),
(NULL, 'suggest_sell', 'I have %item and need more.'),
(NULL, 'suggest_sell', 'Have %item. Who wants to buy for %gold?'),
(NULL, 'suggest_sell', 'Anyone WTB %item for %gold?'),
(NULL, 'suggest_sell', 'What about %item? For %gold.'),
(NULL, 'suggest_sell', 'Who said I am a bastard? %item for %gold is a good price.'),
(NULL, 'suggest_sell', 'I am selling %item? Just %gold.'),
(NULL, 'suggest_sell', 'LFG for farming. You can still buy %item I have for %gold.'),
(NULL, 'suggest_sell', 'Sold almost everything today. Still have %item for %gold.'),
(NULL, 'suggest_sell', 'What use for trade chat? Of course to sell %item for %gold.'),
(NULL, 'suggest_sell', 'Can anyone beat the price of %gold for %item?'),
(NULL, 'suggest_sell', 'Wanna stop trade chat? Just buy %item? For %gold!'),
(NULL, 'suggest_sell', 'Everybody spams in trade chat. Me too - %gold for %item!'),
(NULL, 'suggest_sell', 'Is %item any use? Just selling it for %gold.'),
(NULL, 'suggest_sell', 'I have %item ready to sell you for %gold.'),
(NULL, 'suggest_sell', 'Did nothing yesterday but have got %item. Selling it for %gold.'),
(NULL, 'suggest_sell', 'Farmed yesterday and got %item. Anyone wtb for %gold?'),
(NULL, 'suggest_sell', 'Bought %item yesterday. Anyone needs it for %gold?'),
(NULL, 'suggest_sell', 'Who asked for %item? The price is the same - %gold.'),
(NULL, 'suggest_sell', 'I sill have %item. WTB for %gold?'),
(NULL, 'suggest_sell', 'I used to have more than %item. Now needs to sell it for %gold.'),
(NULL, 'suggest_sell', 'I wish I have more than %item. You could buy it for %gold anyways.'),
(NULL, 'suggest_sell', 'What use for your gold? To buy my %item for %gold.'),
(NULL, 'suggest_sell', 'Please spare some gold for me. You can buy %item for %gold.'),
(NULL, 'suggest_sell', 'Is %gold is a good price for %item?'),
(NULL, 'suggest_sell', 'Just bought yesterday %items, but do not need it anymore. Anyone wants for %gold?'),
(NULL, 'suggest_sell', 'I am going to post %item on the AH but you can buy it now cheaper just for %gold.'),
(NULL, 'suggest_sell', 'Why the #!@ have I bought %item? Anyone needs it for %gold?')
;

DROP TABLE IF EXISTS `ahbot_history`;
DROP TABLE IF EXISTS `ahbot_category`;
DROP TABLE IF EXISTS `ahbot_price`;

CREATE TABLE `ahbot_history` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `buytime` bigint(20) NOT NULL,
  `item` bigint(20) NOT NULL,
  `bid` bigint(20) NOT NULL,
  `buyout` bigint(20) NOT NULL,
  `won` bigint(20) NOT NULL,
  `category` varchar(45) DEFAULT NULL,
  `auction_house` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `won` (`won`),
  KEY `category` (`category`),
  KEY `auction_house` (`auction_house`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ahbot_category` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `category` varchar(45) DEFAULT NULL,
  `multiplier` decimal(20, 2) NOT NULL,
  `max_auction_count` bigint(20) NOT NULL,
  `expire_time` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `helper` (`category`, `multiplier`, `expire_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ahbot_price` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `item` varchar(45) DEFAULT NULL,
  `price` decimal(20, 2) NOT NULL,
  `auction_house` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ahbot_price_item` (`item`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create index idx_ahbot_history_item on ahbot_history(item);
create index idx_ahbot_history_buytime on ahbot_history(buytime);
create index idx_ahbot_price_auction_house on ahbot_price(auction_house);
create index idx_ai_playerbot_guild_tasks_value on ai_playerbot_guild_tasks(value);